export const GET_REGISTER_RESPONSE = 'GET_RESPONSE_RESPONSE';
export const GET_REGISTER_RESPONSE_SUCCESS = 'GET_RESPONSE_RESPONSE_SUCCESS';
export const GET_REGISTER_RESPONSE_FAILURE = 'GET_RESPONSE_RESPONSE_FAILURE';
export const GET_REGISTER_RESPONSE_PROGRESS = 'GET_RESPONSE_RESPONSE_PROGRESS';
