export const SAVE_TOKEN_PROGRESS = 'SAVE_TOKEN_PROGRESS';
export const SAVE_TOKEN_SUCCESS = 'SAVE_TOKEN_SUCCESS';
export const SAVE_TOKEN_FAILURE = 'SAVE_TOKEN_FAILURE';
export const SAVE_TOKEN = 'SAVE_TOKEN';
